nymea/nymea-plugins-modbus

modbus/modbusrtumaster.cpp
modbus/modbusrtumaster.h
modbus/modbustcpmaster.cpp
modbus/modbustcpmaster.h
modbuscommander/README.md
modbuscommander/integrationpluginmodbuscommander.cpp
modbuscommander/integrationpluginmodbuscommander.h
modbuscommander/integrationpluginmodbuscommander.json
modbuscommander/translations/7dda1b6d-c37e-4c9f-a696-1666f9de66e6-de.ts
modbuscommander/translations/7dda1b6d-c37e-4c9f-a696-1666f9de66e6-en_US.ts

Modbus Commander: improve setup

---

wallbe/integrationpluginwallbe.cpp
wallbe/integrationpluginwallbe.json

Wallbe: Updated extendevcharger interface

---

debian/control

Update dependency to renamed libnymea-dev package

---

modbus/modbusrtumaster.cpp
modbuscommander/integrationpluginmodbuscommander.cpp
modbuscommander/integrationpluginmodbuscommander.h
modbuscommander/integrationpluginmodbuscommander.json
modbuscommander/modbuscommander.pro

ModbusCommander: Use new modbus RTU hardware resource for the modbus commander plugin

---

debian/control
unipi/unipi.cpp
unipi/unipi.h
unipi/unipi.pro

Unipi: Update to libnymea-gpio

---

unipi/unipi.h

Actually a no change reubuild to relink new nymea-gpio ABI

UniPi: Fix gpio includes

---

modbus/modbusdatautils.cpp
modbus/modbusdatautils.h
modbus/tools/README.md
modbus/tools/generate-connection.py

Add modbus class generator tools 

---

sunspec/integrationpluginsunspec.json
sunspec/solaredgebattery.cpp
wallbe/integrationpluginwallbe.json
webasto/integrationpluginwebasto.cpp
webasto/integrationpluginwebasto.json

I think they're tested on the test setups... 
Intentionally skipping this for now as it would conflict with other branches too much.

Update to new energystorage interface

---

unipi/unipi.cpp

Unipi: Update unipi to libnymea-gpio changes

---

sunspec/meta.json

Sunspec: Add category to meta.json

---

wallbe/integrationpluginwallbe.cpp
wallbe/integrationpluginwallbe.json

Wallbe: Fix eventTypeId -> actionParamTypeId typo

---

sunspec/README.md
sunspec/integrationpluginsunspec.cpp
sunspec/integrationpluginsunspec.json
sunspec/translations/cb4bdec6-cf2c-4a0f-9709-42d951ca2d8b-en_US.ts

SunSpec: Remove Kostal sunspec connection in favor of custom modbus implementation

---

sunspec/integrationpluginsunspec.json

Sunspec: Set weak discovery type

---

wallbe/integrationpluginwallbe.json
webasto/integrationpluginwebasto.json

Add smartmeterconsumer interface due to evcharger interface update

---

huawei/integrationpluginhuawei.json

Huawei: Update state cache behaviour

---

modbus/tools/README.md
modbus/tools/connectiontool/modbusrtu.py
modbus/tools/connectiontool/modbustcp.py
modbus/tools/connectiontool/toolcommon.py
modbus/tools/generate-connection.py

Restructure modbus connection tool

---

libnymea-modbus/tools/connectiontool/toolcommon.py

modbus-tool: Add register read finished signal

---

libnymea-modbus/modbustcpmaster.cpp
libnymea-sunspec/sunspecconnection.cpp
libnymea-sunspec/sunspecconnection.h
libnymea-sunspec/sunspecmodel.cpp
sunspec/integrationpluginsunspec.cpp
sunspec/integrationpluginsunspec.h
sunspec/integrationpluginsunspec.json

SunSpec: Introduce reconnect on to many timeout errors and update connected state handling

---

libnymea-modbus/tools/generate-connection.py

modbus-tool: Fix issue #69 : make json without blocks work again 

---

debian/control
debian/nymea-modbus-cli.install.in
nymea-modbus-cli/README.md
nymea-modbus-cli/main.cpp
nymea-modbus-cli/nymea-modbus-cli.pro
nymea-plugins-modbus.pro

nymea-modbus-cli: Add nymea modbus tool for testing purposes

---

phoenixconnect/integrationpluginphoenixconnect.json

PhoenixConnect: Update maximum values

---

kostal/integrationpluginkostal.cpp

Kostal: Add total energy returned to grid property

---

libnymea-modbus/modbustcpmaster.cpp

Add host address to error debug prints

---

schrack/cion-registers.json
schrack/integrationpluginschrack.cpp

Schrack: Only complete the setup if reading a register actually works

---

phoenixconnect/README.md
phoenixconnect/integrationpluginphoenixconnect.cpp
phoenixconnect/integrationpluginphoenixconnect.json
phoenixconnect/phoenixconnect-registers.json
phoenixconnect/phoenixconnect.pro
phoenixconnect/phoenixdiscovery.cpp
phoenixconnect/phoenixdiscovery.h
phoenixconnect/translations/0de5bbd2-0dad-4727-9a17-3ee149106048-de.ts

PhoenixConnect: Improve plugin stability

---

alphainnotec/integrationpluginalphainnotec.cpp
huawei/huaweifusionsolardiscovery.cpp
huawei/huaweifusionsolardiscovery.h
idm/integrationpluginidm.cpp
kostal/kostaldiscovery.cpp
modbuscommander/integrationpluginmodbuscommander.cpp
mtec/integrationpluginmtec.cpp
stiebeleltron/integrationpluginstiebeleltron.cpp
sunspec/integrationpluginsunspec.cpp
webasto/integrationpluginwebasto.cpp

Clean up network device discovery replies due to mechanism update

---

nymea-modbus-cli/main.cpp

Add a parameter to write registers to the cli

---

sunspec/integrationpluginsunspec.cpp
sunspec/integrationpluginsunspec.json

SunSpec: Fix storage state and improve overall generic connection

---

mennekes/amtronecudiscovery.cpp
mennekes/amtronhcc3discovery.cpp

Mennekes: Don't filter for MAC address manufacturer during discovery

---

phoenixconnect/integrationpluginphoenixconnect.cpp
phoenixconnect/integrationpluginphoenixconnect.json

Phoenix: Handle emeter register underflow on wallbox and make discovery weak

---

sma/integrationpluginsma.cpp
sma/integrationpluginsma.h

SMA: Round total energy counters to 2 digits

---

schrack/integrationpluginschrack.cpp

Schrack: Fix connection leak on failed setup

---

sma/integrationpluginsma.cpp
sma/sunnywebbox/sunnywebbox.cpp
sma/sunnywebbox/sunnywebbox.h

SMA: fix power parsing for SunnyWebBox

---

modbuscommander/integrationpluginmodbuscommander.cpp
modbuscommander/integrationpluginmodbuscommander.json
modbuscommander/translations/7dda1b6d-c37e-4c9f-a696-1666f9de66e6-de.ts
modbuscommander/translations/7dda1b6d-c37e-4c9f-a696-1666f9de66e6-en_US.ts

modbuscommander: update actions and fix RTU crash on resource removal

---

mennekes/amtronecudiscovery.cpp
mennekes/amtronhcc3discovery.cpp
mennekes/integrationpluginmennekes.cpp
mennekes/translations/c7c3c65c-a0cc-4ab1-90d8-4ad05bfcdc38-en_US.ts

Mennekes: Discard unknown discovery results

---

schrack/cion-registers.json
schrack/integrationpluginschrack.cpp
schrack/integrationpluginschrack.json

Schrack: Add firmware version state

---

schrack/README.md
schrack/cion-registers.json
schrack/ciondiscovery.cpp
schrack/ciondiscovery.h
schrack/integrationpluginschrack.cpp
schrack/integrationpluginschrack.json
schrack/schrack.pro
schrack/translations/600beeb5-5c34-49fc-b2af-8f83c1b11eab-de.ts

Schrack: Rework discovery

---

drexelundweiss/integrationplugindrexelundweiss.json

Drexel&Weiss: Add min/max values to co2sensor

---

libnymea-modbus/tools/generate-connection.py

ModbusRtu connection: Check reachablility in constructor

---

huawei/integrationpluginhuawei.cpp
huawei/integrationpluginhuawei.h

huawei: Set energy states to 0 if not connected and filter invalid energy counter values 

---

sma/integrationpluginsma.cpp
sma/integrationpluginsma.h

SMA: set energy values to 0 on disconnected

---

sunspec/integrationpluginsunspec.cpp
sunspec/integrationpluginsunspec.h

SunSpec: Fix meter phase power and phase current signs

---

libnymea-modbus/modbusdatautils.cpp
libnymea-modbus/modbusdatautils.h
libnymea-modbus/tools/README.md
libnymea-modbus/tools/connectiontool/toolcommon.py
libnymea-modbus/tools/generate-connection.py

modbus-tool: Introduce string endianess

---

nymea-modbus-cli/main.cpp

nymea-modbus-cli: Add modbus RTU functionality

---

sma/integrationpluginsma.cpp
sma/integrationpluginsma.h
sma/integrationpluginsma.json
sma/speedwire/speedwire.h
sma/speedwire/speedwirediscovery.cpp
sma/speedwire/speedwirediscovery.h
sma/speedwire/speedwireinterface.cpp
sma/speedwire/speedwireinterface.h
sma/speedwire/speedwireinverter.cpp
sma/speedwire/speedwireinverter.h

SMA: Improve speedwire protocol handling and add SMA battery

---

modbuscommander/integrationpluginmodbuscommander.json

ModbusCommander: Fix value state name typo

---

sma/integrationpluginsma.cpp
sma/speedwire/speedwireinverter.cpp
sma/speedwire/speedwireinverter.h

SMA: improve inverter value reading and enable battery

---

sunspec/integrationpluginsunspec.cpp
sunspec/sunspecdiscovery.cpp
sunspec/sunspecdiscovery.h

SunSpec: Fix autoremove devices if the model does not exist any more

---

nymea-modbus-cli/main.cpp

Note: the exception response to string conversion is intentionally copied here from the libnymea-modbus to keep the tool a Qt only dependency / standalone binary. 

nymea-modbus-cli: Add exception code parsing

---

huawei/README.md
huawei/huawei-fusion-solar-registers.json
huawei/huaweifusionsolar.cpp
huawei/huaweifusionsolar.h
huawei/huaweifusionsolardiscovery.cpp
huawei/huaweifusionsolardiscovery.h
huawei/integrationpluginhuawei.cpp
huawei/integrationpluginhuawei.json
huawei/translations/fc3e4509-47f3-4622-9bc4-0a90fe2b6262-en_US.ts

Huawei: Extend discovery to scan for multiple modbus servers

---

sma/integrationpluginsma.cpp
sma/integrationpluginsma.h
sma/speedwire/speedwire.h
sma/speedwire/speedwirediscovery.cpp
sma/speedwire/speedwirediscovery.h
sma/speedwire/speedwireinterface.cpp
sma/speedwire/speedwireinterface.h
sma/speedwire/speedwireinverter.cpp
sma/speedwire/speedwireinverter.h
sma/speedwire/speedwiremeter.cpp
sma/speedwire/speedwiremeter.h

SMA: Improve speedwire interface handling and sharing

---

mennekes/README.md
mennekes/integrationpluginmennekes.cpp
mennekes/integrationpluginmennekes.json

Mennekes: Add solarChargingMode state to Compact20s

---

mennekes/integrationpluginmennekes.cpp

Mennekes: Use voltage instead of current to determine connected phases

---

schrack/integrationpluginschrack.cpp

Schrack: Fix a crash when the setup of the wallbox fails

---

schrack/integrationpluginschrack.cpp
schrack/integrationpluginschrack.h
schrack/integrationpluginschrack.json

Schrack: Add setting for connected phases

---

alphainnotec/integrationpluginalphainnotec.cpp
amperfied/integrationpluginamperfied.cpp
huawei/huaweifusionsolar.cpp
huawei/huaweifusionsolardiscovery.cpp
huawei/integrationpluginhuawei.cpp
idm/integrationpluginidm.cpp
kostal/integrationpluginkostal.cpp
kostal/kostaldiscovery.cpp
libnymea-modbus/modbustcpmaster.cpp
libnymea-modbus/modbustcpmaster.h
libnymea-modbus/tools/connectiontool/modbustcp.py
libnymea-modbus/tools/connectiontool/toolcommon.py
libnymea-modbus/tools/generate-connection.py
mennekes/integrationpluginmennekes.cpp
modbuscommander/integrationpluginmodbuscommander.cpp
modbuscommander/integrationpluginmodbuscommander.h
mtec/mtec.cpp
mtec/mtec.h
mypv/integrationpluginmypv.cpp
mypv/integrationpluginmypv.h
phoenixconnect/integrationpluginphoenixconnect.cpp
sma/integrationpluginsma.cpp
sma/modbus/smamodbusdiscovery.cpp
stiebeleltron/integrationpluginstiebeleltron.cpp
webasto/webasto.cpp
webasto/webasto.h

modbus-tool: Allow creating multiple connections on one ModbusTcpMaster

---

schrack/cion-registers.json
schrack/integrationpluginschrack.cpp

Schrack: Improve some debug prints

---

amperfied/README.md
amperfied/amperfied-registers.json
amperfied/amperfied.pro
amperfied/amperfiedconnectdiscovery.cpp
amperfied/amperfiedconnectdiscovery.h
amperfied/integrationpluginamperfied.cpp
amperfied/integrationpluginamperfied.json
phoenixconnect/phoenixdiscovery.cpp

Amperfied: Add support for connect.solar and connect.business

---

huawei/huawei-fusion-solar-registers.json
huawei/huawei-registers.json
huawei/huaweifusionsolar.cpp
huawei/integrationpluginhuawei.cpp
huawei/translations/fc3e4509-47f3-4622-9bc4-0a90fe2b6262-en_US.ts

- [Y] Make sure the pull request's title is of format "Plugin name: Add support for xyz" or "New plugin: Plugin name"
- [Y] Did you test the changes on hardware, if not (e.g. absence of required hardware), please mention a person to confirm it has been tested.
- [N/A] Did you update the plugin's README.md accordingly?
- [Y] Did you update translations (`cd builddir && make lupdate`)?

Huawei: smartmeter add totals

---

LICENSE.LGPL3

Adding LGPL3 license file

---

sunspec/integrationpluginsunspec.cpp
sunspec/integrationpluginsunspec.h

SunSpec: Filter out invalid energy produced values

---

huawei/huaweifusionsolar.cpp
huawei/huaweifusionsolar.h

Huawei: Update battery behaviour depending on the battery state

---

sma/speedwire/speedwireinverter.cpp

SMA: Update value reading filter

---

nymea-modbus-cli/README.md

Update nymea-modbus-cli documentation

---

sunspec/integrationpluginsunspec.cpp

SunSpec: Update read block behavior and prevent duplicated things

---

wattsonic/integrationpluginwattsonic.cpp
wattsonic/integrationpluginwattsonic.h
wattsonic/wattsonic-registers.json

Wattsonic: Update connection behavior and fix PV production value

---

mennekes/integrationpluginmennekes.cpp

Menekes:  Fix AmtronECU charging state for firmware version < 5.22

---

mennekes/integrationpluginmennekes.cpp
mennekes/integrationpluginmennekes.json
mennekes/translations/c7c3c65c-a0cc-4ab1-90d8-4ad05bfcdc38-de.ts

Mennekes: Update translations and allow IP based connections

---

libnymea-modbus/libnymea-modbus.pro
libnymea-modbus/modbustcpconnection.h
libnymea-modbus/tools/generate-connection.py

modbus-tool: Create TCP connection pure virtual base class

---

pcelectric/README.md

PC-Electric: Add integration plugin documentation

---

pcelectric/EV11.3-registers.json
pcelectric/integrationpluginpcelectric.cpp
pcelectric/integrationpluginpcelectric.h
pcelectric/integrationpluginpcelectric.json
pcelectric/pcewallbox.cpp
pcelectric/pcewallbox.h
pcelectric/translations/aa7ff833-a8e0-45cc-a1ef-65f05871f272-de_DE.ts
pcelectric/translations/aa7ff833-a8e0-45cc-a1ef-65f05871f272-en_US.ts

PCE: Add serial number as paramter

---

LICENSE.GPL3
debian/copyright
libnymea-modbus/tools/connectiontool/modbusrtu.py
libnymea-modbus/tools/connectiontool/modbustcp.py
libnymea-modbus/tools/connectiontool/toolcommon.py
libnymea-modbus/tools/generate-connection.py

Update license and debian copyright

---

sma/speedwire/speedwireinterface.cpp
sma/speedwire/speedwireinterface.h

SMA: Fix circular disovery on multiple interfaces in the same network

---

pcelectric/EV11.3-registers.json
pcelectric/integrationpluginpcelectric.cpp
pcelectric/integrationpluginpcelectric.h
pcelectric/pcewallbox.cpp
pcelectric/pcewallbox.h

PcElectric: Update action handling based on single register

---

vestel/evc04discovery.cpp

Vestel: Improve Vestel/Webasto discovery

---

wattsonic/integrationpluginwattsonic.cpp
wattsonic/integrationpluginwattsonic.json
wattsonic/wattsonic-registers.json
wattsonic/wattsonicdiscovery.cpp
wattsonic/wattsonicdiscovery.h

Wattsonic: Add modbus slave ID as discovery parameter

---

alphainnotec/integrationpluginalphainnotec.cpp
alphainnotec/integrationpluginalphainnotec.h
alphainnotec/integrationpluginalphainnotec.json

Alphainnotec: Update to networkdevice interface

---

huawei/huaweifusionsolardiscovery.cpp
huawei/huaweifusionsolardiscovery.h
huawei/integrationpluginhuawei.cpp
huawei/integrationpluginhuawei.h
huawei/integrationpluginhuawei.json

Huawei: Update to networkdevice interface

---

kostal/integrationpluginkostal.cpp
kostal/integrationpluginkostal.h
kostal/integrationpluginkostal.json
kostal/kostaldiscovery.cpp
kostal/kostaldiscovery.h

Kostal: Update to networkdevice interface

---

modbuscommander/integrationpluginmodbuscommander.cpp

Modbuscommander: Update network device discovery

---

mtec/integrationpluginmtec.cpp
mtec/integrationpluginmtec.h
mtec/integrationpluginmtec.json
mtec/mtec.cpp
mtec/mtec.h

MTec: Update to networkdevice interface

---

sma/integrationpluginsma.cpp
sma/integrationpluginsma.json
sma/modbus/smamodbusbatteryinverterdiscovery.cpp
sma/modbus/smamodbusbatteryinverterdiscovery.h
sma/modbus/smamodbussolarinverterdiscovery.cpp
sma/modbus/smamodbussolarinverterdiscovery.h
sma/speedwire/speedwirediscovery.cpp
sma/speedwire/speedwirediscovery.h
sma/speedwire/speedwireinverter.cpp
sma/speedwire/speedwireinverter.h
sma/sunnywebbox/sunnywebbox.cpp
sma/sunnywebbox/sunnywebbox.h
sma/sunnywebbox/sunnywebboxdiscovery.cpp
sma/sunnywebbox/sunnywebboxdiscovery.h

SMA: Update to networkdevice interface

---

solax/integrationpluginsolax.cpp
solax/integrationpluginsolax.json
solax/solaxdiscovery.cpp
solax/solaxdiscovery.h

Solax: Update to networkdevice interface

---

stiebeleltron/integrationpluginstiebeleltron.cpp
stiebeleltron/integrationpluginstiebeleltron.h
stiebeleltron/integrationpluginstiebeleltron.json

Stiebeleltron: Update to the networkdevice interface

---

inro/pantabox-registers.json
inro/pantabox.cpp

Inro: Pantabox improve connected handling

---

schrack/integrationpluginschrack.json

Schrack: Default to 3-phase connection

---

pcelectric/EV11.3-registers.json
pcelectric/integrationpluginpcelectric.cpp
pcelectric/integrationpluginpcelectric.json
pcelectric/pcelectricdiscovery.cpp
pcelectric/pcewallbox.cpp
pcelectric/pcewallbox.h
pcelectric/translations/aa7ff833-a8e0-45cc-a1ef-65f05871f272-de_DE.ts
pcelectric/translations/aa7ff833-a8e0-45cc-a1ef-65f05871f272-en_US.ts

PCE: Add new settings and adopt to firmware 0.22
